### ISSUE TITLE
Provide status indicator for backend API

### ISSUE THREAD

**Issue by abitrolly** [asadovka/cyb_web2#11]
We need a quick status indicator that show that API URL are offline or misconfigured. This may grow up into separate `Cybernode` tab on UI interface, but right now anything on the main page would do.

As a wish, it would be nice to get this panel extendable, so that anybody could easily add more indicators or checks against backend API there. By modifying code and sending PR, or in other convenient way.

**Comment by abitrolly** [comment]
Fixed by #12.

**Comment by mastercyb** [comment]
@asadovka I dont understan this issue
