### ISSUE TITLE
Browser shell requirements

### ISSUE THREAD

**Issue by asadovka** [asadovka/cyb_web2#128]
- [x] update SR doc

**Comment by mastercyb** [comment]
There is a reference to deliverables?

**Comment by asadovka** [comment]
@xhipster sure:
https://github.com/cybercongress/cyber-browser/blob/master/docs/Software_Requirements.md#0-browser-menu--header

**Comment by asadovka** [comment]
https://github.com/cybercongress/cyb/pull/177

**Comment by asadovka** [comment]
approved
