### ISSUE TITLE
Change container name to correspond to repository name

### ISSUE THREAD

**Issue by abitrolly** [asadovka/cyb_web2#14]
As a potential repository contributor I need to find out the source that builds `cui-browser`. See also https://github.com/cyberFund/cyber-ui/commit/2ae7e74cb6f0989705ec69e4bf9cadc73086d06e why having different names for software repo and its image is inconvenient.

Until we have our frontend split into several containers, there is no need in convention like in `cyber-markets` that is used to split market components into pieces. "Foolish consistency is the hobgoblin of little minds". 

https://www.python.org/dev/peps/pep-0008/#a-foolish-consistency-is-the-hobgoblin-of-little-minds

**Comment by abitrolly** [comment]
Added http://staging.cyber.fund DNS

**Comment by abitrolly** [comment]
Problem with rename is that it breaks deployment configs in `cyber-markets` repo, which also deploys `frontend` for production and development cluster - https://github.com/cyberFund/cyber-markets/search?utf8=%E2%9C%93&q=cui-browser&type=

We need to decide on repo that will host deploy scripts that are common for all components.

**Comment by abitrolly** [comment]
@litvintech @mgergalov @hleb-albau we need to reach a consensus on Docker image names. The problem with current naming that neither I, nor @litvintech could find image generated from this `cyber-ui` repository in our https://hub.docker.com/u/cybernode/

I propose a rule to name docker image the same way as repository if we build only one image from that source. If we build multiple containers from one repo, then a naming should be documented (and discussed) separately for that repo.

Right now it is clear that containers are not products and we can not deliver single `cyber-browser` product through DockerHub. We need some other place to keep configurations that binds **containers into products**, so that we can discover products with `cybernode` and install them with user friendly `cyber-markets` (API), `cyber-search` (API), `cyber-ui` (frontend) or `cyber-browser` (everything together).

**Comment by cyborgshead** [comment]
@abitrolly please finish this and rename cyber-ui to cyber-browser without issues with dependencies.
