### ISSUE TITLE
Actualize symbols in sketch files

### ISSUE THREAD

**Issue by asadovka** [asadovka/cyb_web2#170]
- [x] Give every symbol unique name
- [x] Move all symbols to external library

**Comment by Olga584** [comment]
@asadovka please, review file. https://github.com/cybercongress/cyb/blob/master/design/symbol.sketch

**Comment by asadovka** [comment]
@Olga584 is there only main page symbols?

**Comment by asadovka** [comment]
@Olga584 Please create groups for symbols
