### ISSUE TITLE
Update cyb landing design

### ISSUE THREAD

**Issue by cyberadmin** [asadovka/cyb_web2#220]

**Comment by asadovka** [comment]
Readme logo:

![image](https://user-images.githubusercontent.com/17406355/42756178-b3f7132a-8903-11e8-9aac-d8f50899bd81.png)

**Comment by asadovka** [comment]
[current version](https://github.com/cybercongress/cyb/tree/master/design/landing)

**Comment by mastercyb** [comment]
Круто!
Пропоузал по небольшим правкам:
1. Слоган: вместо NextGen browser and dapp platfrom давай вот это `web3 browser you love`
2. Кнопка:  должна быть download
3. Вместо start browsing обычная поисковая строка
4. Подвал: вмексто медиума - ссылка на наш блог
