### ISSUE TITLE
Git history takes 300mb

### ISSUE THREAD

**Issue by hleb-albau** [asadovka/cyb_web2#236]
Current fresh-cloned repository takes 300mb.
```
15M  ./web
11M  ./design
44K  ./docs
24K  ./devops
128K  ./cli
8.0K  ./.circleci
271M  ./.git
296M  .
```
May be we storing some freq-changing binaries (such as design)?

**Comment by asadovka** [comment]
the solution is to create new separate repo for cyb and migrate all design sources to another new repo.

**Comment by asadovka** [comment]
old repos:
https://github.com/cybercongress/cyb_web2
https://github.com/cybercongress/cyb-parity

new repo:
https://github.com/cybercongress/cyb

design repo:
https://github.com/cybercongress/cyberdesign
