### ISSUE TITLE
Add docs for bringing staging up

### ISSUE THREAD

**Issue by abitrolly** [asadovka/cyb_web2#27]
In #9 we've made a quick manual deploy of our staging server. Now that [mars came down again](https://github.com/cyberFund/cybernode/issues/114#issuecomment-348967756) we need to repeat the setup.

And then automate it.

**Comment by abitrolly** [comment]
Docs are maturing at https://github.com/cyberFund/cyber-ui/blob/master/docs/staging.md

**Comment by cyborgshead** [comment]
@abitrolly need test and remove dependency or move docs to cybernode
