### ISSUE TITLE
Refactor crowdsale name

### ISSUE THREAD

**Issue by mastercyb** [asadovka/cyb_web2#29]
Code and UX
- [ ] crowdsale => ico
- [ ] crowdsales => icos
- [ ] Crowdsale => ICO
- [ ] Crowdsales => ICOs

Reason: significantly more popular semantics according to Google Trends
![](https://monosnap.com/file/GuqEERPCA9q4luqz6ktbNbAyRfG8zq.png)

**Comment by cyborgshead** [comment]
Will be migrated to cyber-desing for design/analytics.
