### ISSUE TITLE
Reorder links in main menu

### ISSUE THREAD

**Issue by mastercyb** [asadovka/cyb_web2#31]
An order should be the following:
- Blockchains
- Tokens
- Exchanges
- ICOs
- Labels (should be renamed from Funds)
- Analytics
- Cybernode

**Comment by cyborgshead** [comment]
Will be migrated to cyber-desing for design/analytics.

**Comment by cyborgshead** [comment]
@Olga584 Please, reorder links in main menu like @21xhipster described before.
