### ISSUE TITLE
Create price chart for token details

### ISSUE THREAD

**Issue by Pechalka** [asadovka/cyb_web2#33]
use this lib https://vx-demo.now.sh/axis
use rest market api

**Comment by cyborgshead** [comment]
@Pechalka 
1. link to [tokens page details](http://staging.cyber.fund:32500/tokens/SC-BTC)
2. please provide your vision/roadmap to enhancement
3. please set up new issues

**Comment by Pechalka** [comment]
base version implemented, next task will be here https://github.com/cyberFund/cyber-ui/issues/45
