### ISSUE TITLE
Tokens page story - token monitoring

### ISSUE THREAD

**Issue by abitrolly** [asadovka/cyb_web2#34]
As a user I want to know price change (or better % dynamics) in USD of 5 tokens from my portfolio for certain period (week). I want to see tokens, current price is not obligatory, but period is good. @SiarheiSadau 

--- 

Tokens page is for price monitoring, comparing between tokens (selected actual ones).

![screenshot from 2017-12-26 19-31-43](https://user-images.githubusercontent.com/8781107/34360632-9f5f803e-ea73-11e7-9cce-4fbe5cea9b2c.png)

* I don't understand what price is, how is it calculated
* I don't get where the price comes from (which markets)
* I don't understand why it is sorted like this

**Comment by abitrolly** [comment]
What is done so far:

![image](https://user-images.githubusercontent.com/8781107/34946671-d44e3be6-fa18-11e7-82ba-de89846c7743.png)

* [x] front for searching tokens from the list by name (Bitcoin)
  * [ ] front for searching tokens by token (BTC)
* [x] selecting tokens and pinning tokens to the top
* [x] ui reflects current sorting field (hardcoded volume by pair)
* [x] price graph for a week works
  * [ ] price data feed is not valid
    * [ ] not all datapoints are visible
    * [ ] if data are missing, price graph doesn't show it, but interpolates

* [x] we show the price in USD
  * [x] price for tokens that are traded for USD (USD-traded tokens) is valid
    * [ ] docs for price calculations for USD-traded tokens
    * [ ] docs for price calculations for tokens traded for BTC and other tokens is not valid

**Comment by abitrolly** [comment]
Problems:

* [ ] data from chaingear on token page - no info about supply, links are broken, no specification

**Comment by abitrolly** [comment]
Child issues:

* https://github.com/cyberFund/cyber-ui/issues/38
* https://github.com/cyberFund/cyber-ui/issues/36
* https://github.com/cyberFund/cyber-ui/issues/37
* https://github.com/cyberFund/cyber-ui/issues/39

**Comment by cyborgshead** [comment]
@SiarheiSadau Please update status of this issue
@SiarheiSadau @abitrolly We working with concepts/mockups in repository cyber-design, this issue should be migrated to cyber-design repository
