### ISSUE TITLE
Token monitor page summary

### ISSUE THREAD

**Issue by asadovka** [asadovka/cyb_web2#36]
This is th basic concept of main token monitor page:

[https://drive.google.com/file/d/1ImT4HTkLOQyH9BZTyLFVOGEqmFhyXAbD/view?usp=sharing](url)

![tokens](https://user-images.githubusercontent.com/17406355/34411268-5afaee4e-ebde-11e7-9dd4-419294dc7771.png)

**Updates for first release:**
1. Two loadings are used for page: first - to get all pairs, second - to update prices.
2. The price of the token is calculated as the last value of 1H ticker (close price). Price updates every 3 seconds.
3. Price change value (24H) is calculated using open and close price of 24H ticker for tradeable currencies. For example: if the token can be bought for USD, the price change will be calculated for USD, for BTC - traded pairs price change is calculated for BTC and so on.
4. Volume is calculated as volume of trades per 1H for one pair in all included axchanges.
5. Small price graph for 7D price change will be implemented.
6. All coins are displayed in a single page.

**Further development:**
1. Sorting function (by volume, price, cap etc) will be implemented
2. Price will be displayed in several currencies (USD, BTC, ETH) with correct caltulation

**Work blockers:**
1. No correct token supply information. Do we need a chaingear info source, or it wil be calculated using cyber.Search resources.
2. Cross calculations of coin price. Needs a backend improvement.
3. Volume should be calculated using full trading data (all pairs with certain coin, exchanges)
4. Market cap should be calculated using correct token supply data. Type of supplyused is an open question (number of existing coins, number of available coins etc)

**Comment by cyborgshead** [comment]
@SiarheiSadau @abitrolly We working with concepts/mockups in repository cyber-design, this issue should be migrated to cyber-design repository
