### ISSUE TITLE
Coin detailed data page summary

### ISSUE THREAD

**Issue by asadovka** [asadovka/cyb_web2#37]
This is th basic concept of main token monitor page:
![photo5344075524508592280](https://user-images.githubusercontent.com/17406355/34413256-dd211676-ebea-11e7-84e8-2cc81aa4f6dc.jpg)

### Updates for first release:
1. The page consists of 2 sections: static header with coin basic info, market stats and detailed section with switchable tabs, including historical graph, orderbooks, market depth graphs, coin specifications.
2. Market tab shows combined graph of market depth for all exchanges. There will be a function of selecting of displayed exhchanges.
3. Market tab shows order book for 1 selecting exchange for certain trading pair.
4. Market tab shows trades for all selected exchanges.
5. Specs tab displays etailed coin data from chaingear.
6. Links tab displays helpful links, grouped by categories.

### Further development:
1. Add USD, Cap and BTC price graphs with zoom functions to historical graph.
2. Add zoom in/zoom out funtcion for market depth graph.

### Work blockers:
1. Invalid (?) orders (with > 1million USD price). Should be clarified.
2. Problems with step calculation for orderbook price values.
3. No valid data from chaingear (links, specs etc.)

**Comment by abitrolly** [comment]
@Olga584, can you see this?

**Comment by Olga584** [comment]
Yes

**Comment by asadovka** [comment]
Updated concept

https://www.draw.io/#G14ROKNlXYxSuN4HogE2CV1su8brcI7ALa

**Comment by cyborgshead** [comment]
@Pechalka Can you please split this issue to tasks-issues 
@abitrolly @Olga584 @Pechalka What are you thinking about workflow where @Olga584 and @SiarheiSadau  work with concepts (images, tables, drawings)  in repo cyber-desing and when they close issues and finalize mockups (psd, sketch files) then they make reference to final revision of mockups to following issue in repository cyber-ui -> then @Pechalka convert mockups to layouts (html+js).

**Comment by cyborgshead** [comment]
@abitrolly Please help @Olga584 with this setting up cyber-design to this flow and explain this flow (add documentation-README in cyber-design which describe flow)

**Comment by cyborgshead** [comment]
@SiarheiSadau @abitrolly We working with concepts/mockups in repository cyber-design, this issue should be migrated to cyber-design repository
