### ISSUE TITLE
January sprint (08.18-15.18) summary

### ISSUE THREAD

**Issue by asadovka** [asadovka/cyb_web2#38]
Several groups of work blockers were detected:

![photo5384131875569772604](https://user-images.githubusercontent.com/17406355/34832839-a52d9c3c-f6f6-11e7-9fd0-43283a2baa53.jpg)

1. Web version design
2. Mobile version design
3. Chaingear data validation (affects of supply, cap calculations)
4. Trades, price calculation on backend.
5. Graphs (7d change)

**Comment by cyborgshead** [comment]
@SiarheiSadau @abitrolly We working with concepts/mockups in repository cyber-design, this issue should be migrated to cyber-design repository
