### ISSUE TITLE
cyber.Search main page concept

### ISSUE THREAD

**Issue by asadovka** [asadovka/cyb_web2#40]
# cyber.Search main page concept

https://drive.google.com/file/d/1_tSxHHBz5v3M1RQzxe8CzA_TDZjmIht8/view

**Comment by abitrolly** [comment]
Saved to disk - it appeared to be draw.io diagram. Imported to draw.io. Exported as SVG. Committed both to https://github.com/cyberFund/cyber-design/tree/master/cyber-browser/concepts
