### ISSUE TITLE
Speed up container builds

### ISSUE THREAD

**Issue by abitrolly** [asadovka/cyb_web2#7]
CI loop is too long for Web UI. Too much time is wasted waiting for new version to appear at staging.

![image](https://user-images.githubusercontent.com/8781107/33565069-29d73e8a-d92d-11e7-8d38-2c4931895939.png)

In this CircleCI job - https://circleci.com/gh/cyberFund/cyber-ui/17#tests/containers/0 - fetching dependencies takes 30 seconds.
```
added 1173 packages in 28.084s
```
* [ ] cache `npm` dependencies during container build

**Comment by cyborgshead** [comment]
@Pechalka @abitrolly make build container with dependencies like in cybernode

**Comment by mastercyb** [comment]
@asadovka Are you sure this issue has been resolved? @Pechalka
