### ISSUE TITLE
Search results page graphic design

### ISSUE THREAD

**Issue by asadovka** [asadovka/cyb_web2#72]
Sketch design of Search Results Page

**Comment by Olga584** [comment]
![Search results](https://raw.githubusercontent.com/cybercongress/cyber-browser/master/browser-design/Search_Results_Page.png)

**Comment by mastercyb** [comment]
The following things should be fixed:
- [ ] Move values to the left, timestamps to the center
- [ ] `Ethereum Uncle block` => `Ethereum uncle block`
- [ ] Bitcoin transaction case is oversimplified. In reality there at least 2 outputs. Second output is a change. There are a lot of transactions with hundreds of inputs or outputs. @asadovka try to fix this 
- [ ] Different margins between filter objects
- [ ] Alignment of digits always to the right
- [ ] There is no space between 45 and BTC in bitcoin transaction
- [ ] Hashes must be easily copypastable
- [ ] Every object must have a simple way to copypaste IPFS hash. Best location of the thing is top right
- [ ] No `Show more` button. Result must be indefinitely scrollable. Scroll must change index of the result in URL
- [ ] Please use real data on final design. Currently bitcoin hash is fake
- [ ] Please start to include in design mockups imaginable browser bar with URL

**Comment by mastercyb** [comment]
Why do you close this thing? Its not done
