### ISSUE TITLE
Bitcoin protocol block page mockup

### ISSUE THREAD

**Issue by asadovka** [asadovka/cyb_web2#79]
- [x] logical sections (overview, mining, rewards, tx)
- [x] copy address by click
- [x] hints on data fields

**Comment by asadovka** [comment]
cyber-browser/browser-concept/Bitcoin-Bitcoin Cash Block Page.png

cyber-browser/browser-concept/Bitcoin-Bitcoin Cash Block Page.xml

**Comment by abitrolly** [comment]
Mockups are 404.

**Comment by asadovka** [comment]
https://github.com/cybercongress/cyber-browser/blob/master/design/browser_concept.sketch
