### ISSUE TITLE
Ethereum protocol block page mockup

### ISSUE THREAD

**Issue by asadovka** [asadovka/cyb_web2#80]
- [x] logical sections (overview, mining, rewards, tx)
- [x] uncle block structure
- [x] copy address by click
- [x] hints on data fields

**Comment by asadovka** [comment]
https://github.com/cybercongress/cyber-browser/blob/master/browser-concept/Ethereum-Ethereum%20Classic%20Block%20Page.png

https://github.com/cybercongress/cyber-browser/blob/master/browser-concept/Ethereum-Ethereum%20Classic%20Block%20Page.xml

**Comment by abitrolly** [comment]
The same problem - concept links are 404.

**Comment by asadovka** [comment]
https://github.com/cybercongress/cyber-browser/blob/master/design/browser_concept.sketch
