### ISSUE TITLE
Ethereum protocol transaction page mockup

### ISSUE THREAD

**Issue by asadovka** [asadovka/cyb_web2#81]
- [x] logical sections (overview, details, io/out, data)
- [x] copy address by click
- [x] hints on data fields

**Comment by asadovka** [comment]
https://github.com/cybercongress/cyber-browser/blob/master/browser-concept/Ethereum-Ethereum%20Classic%20Transaction%20Page.png

https://github.com/cybercongress/cyber-browser/blob/master/browser-concept/Ethereum-Ethereum%20Classic%20Transaction%20Page.xml

**Comment by mastercyb** [comment]
Ethereum transaction mockup: 
1. Field `Transaction hash` => `Hash` 
2. Field `Status` => `State`. Can be `mempool`, `confirmed`, `finalized`.
3. Don't understand how field `function` is defined.

**Comment by asadovka** [comment]
@21xhipster 
1. Done
2. Done
3. This field is for token transfers.
For example: https://etherscan.io/tx/0x927d5e035874a198a5f63a6513b5bccb67afbe53a93ec1dadace7aa913d66ee9

**Comment by abitrolly** [comment]
Again, links to concepts are broken.

**Comment by asadovka** [comment]
https://github.com/cybercongress/cyber-browser/blob/master/design/browser_concept.sketch
