### ISSUE TITLE
Bitcoin protocol transaction page mockup 

### ISSUE THREAD

**Issue by asadovka** [asadovka/cyb_web2#82]
- [x] logical sections (overview, details, io/out, data)
- [x] copy address by click
- [x] hints on data fields

**Comment by asadovka** [comment]
https://github.com/cybercongress/cyber-browser/blob/master/browser-concept/Bitcoin-Bitcoin%20Cash%20Transaction%20Page.png

https://github.com/cybercongress/cyber-browser/blob/master/browser-concept/Bitcoin-Bitcoin%20Cash%20Transaction%20Page.xml

**Comment by mastercyb** [comment]
@asadovka In Bitcoin case input and output data is input output specific. Current version is confusing if there are more man 1 output or input. Would love to see common mockup for both ethereum and bitcoin cases. Pray for merging with this cybercongress/cyber-browser#81 AND defining chain specific block of information

**Comment by abitrolly** [comment]
Concept links are broken. Referencing commits that add them helps to find them in cases like this.

**Comment by asadovka** [comment]
@abitrolly thank you! mockups are now migrated to sketch app.

here is the valid link:

https://github.com/cybercongress/cyber-browser/blob/master/design/browser_concept.sketch

**Comment by abitrolly** [comment]
And how much I need to pay to open this link from Linux? :D

**Comment by mastercyb** [comment]
@abitrolly We are testing different processes to find the best that remove our pain. Agree that Zeplin is not perfect, but if it solve the stuff we want, we will let it go. BTW `.sketch` is also problematic for Linux, but it seems that there is no alternative around.

**Comment by abitrolly** [comment]
I can not recommend people to use open source tools they are not interested in developing skills in, or just "don't like", but there is https://alternativeto.net/software/sketch/?platform=linux There is no funding goes into supporting open source art in Belarus, so people prefer to use pirated Adobe software and have no idea that they can participate in something greater. )
