### ISSUE TITLE
Bitcoin protocol transaction page graphic design

### ISSUE THREAD

**Issue by asadovka** [asadovka/cyb_web2#83]

**Comment by Olga584** [comment]
![Bitcoin transaction page](https://raw.githubusercontent.com/cybercongress/cyber-browser/master/browser-design/Search_Bitcoin-Bitcoin_Cash_Transaction_Page.png)

**Comment by asadovka** [comment]
[sketch](https://github.com/cybercongress/cyb/blob/master/design/apps/explorer/blockchain%20explorer.sketch)

![image](https://user-images.githubusercontent.com/17406355/42725404-9c27f2e2-878b-11e8-91b7-6a36637b3354.png)
