### ISSUE TITLE
Ethereum protocol transaction page graphic design

### ISSUE THREAD

**Issue by asadovka** [asadovka/cyb_web2#84]

**Comment by Olga584** [comment]
https://github.com/cybercongress/cyber-browser/blob/master/browser-design/Search_Ethereum-Ethereum_Classic_Transaction_Page.png

**Comment by asadovka** [comment]
[sketch](https://github.com/cybercongress/cyb/blob/master/design/apps/explorer/blockchain%20explorer.sketch)

![image](https://user-images.githubusercontent.com/17406355/42725379-2b5290ae-878b-11e8-853a-27dcd55292c8.png)
