### ISSUE TITLE
Bitcoin protocol block page graphic design

### ISSUE THREAD

**Issue by asadovka** [asadovka/cyb_web2#85]

**Comment by Olga584** [comment]
https://github.com/cybercongress/cyber-browser/blob/master/browser-design/Search_Bitcoin-Bitcoin_Cash_Block_Page.png

**Comment by asadovka** [comment]
[sketch](https://github.com/cybercongress/cyb/blob/master/design/apps/explorer/blockchain%20explorer.sketch)

tab1
![image](https://user-images.githubusercontent.com/17406355/42725352-de8a674c-878a-11e8-93fc-0e7e1f529be7.png)

tab2
![image](https://user-images.githubusercontent.com/17406355/42725358-ecfa9842-878a-11e8-897f-e5a4bd0dd67d.png)
