### ISSUE TITLE
Ethereum protocol block page graphic design

### ISSUE THREAD

**Issue by asadovka** [asadovka/cyb_web2#86]
block page
uncle block page

**Comment by Olga584** [comment]
https://github.com/cybercongress/cyber-browser/blob/master/browser-design/Search_Ethereum-Ethereum_Classic_Block_Page.png

https://github.com/cybercongress/cyber-browser/blob/master/browser-design/Search_Ethereum-Ethereum_Classic_Block_Page_2.png

**Comment by mastercyb** [comment]
@Olga584 Please, instead of links embed pictures in issues like [here](https://github.com/cybercongress/cyber-browser/issues/83)

**Comment by asadovka** [comment]
[sketch](https://github.com/cybercongress/cyb/blob/master/design/apps/explorer/blockchain%20explorer.sketch)

Block

![image](https://user-images.githubusercontent.com/17406355/42725307-730a7da4-878a-11e8-9bd7-62e820687275.png)

Uncle

![image](https://user-images.githubusercontent.com/17406355/42725314-86c217d0-878a-11e8-8092-9c1bb5091385.png)
