### ISSUE TITLE
Create stage server for frontend and chaingear-api

### ISSUE THREAD

**Issue by Pechalka** [asadovka/cyb_web2#9]
Now we have two docker images for frontend and chaingear api. Need public stage server for testing configuration. Need script to build containers, and run container configuration on staging server.

**Comment by abitrolly** [comment]
Because we need to move fast, we setup CircleCI, which is now failing at https://circleci.com/gh/cyberFund/cyber-ui/1

Need to add config with specific instructions. Better copy from `cyber-search` and modify.

**Comment by abitrolly** [comment]
Containers for all components - `cyber-ui`, `cyber-markets` and `cyber-search` are automatically built using CircleCI and deployed to DockerHub - https://circleci.com/gh/cyberFund

`chaingear-api` is manually deployed.

**Comment by abitrolly** [comment]
2ae7e74cb6f0989705ec69e4bf9cadc73086d06e sets default conventions (ports) for running all containers on a single host (`cybernode`).

- `cyber-ui :32500`
- `chaingear-api :32600`
- `cyber-search-api :32700`
- `cyber-markets-api :32800`

**Comment by abitrolly** [comment]
Staging is up with the status indicator (#11) http://staging.cyber.fund:32500/cybernode
