### ISSUE TITLE
Move conceptualization process to Sketch

### ISSUE THREAD

**Issue by mastercyb** [asadovka/cyb_web2#93]

**Comment by asadovka** [comment]
migrate block, transaction, contract . Deleted MVP folders.
https://github.com/cybercongress/cyber-browser/commit/69dea39c8de5c772a2f11ee6b495a6890e1be4ba
https://github.com/cybercongress/cyber-browser/commit/08748687857f04b6b89814fa592c7b8565280bf1

**Comment by asadovka** [comment]
concept folder is deleted. all sketch files are in actual state. (mockups are inside). fro this moment all work will be in sketch.
